// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="LFE_LFE,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=7.281000,HLS_SYN_LAT=4,HLS_SYN_TPT=2,HLS_SYN_MEM=64,HLS_SYN_DSP=0,HLS_SYN_FF=413,HLS_SYN_LUT=2067,HLS_VERSION=2020_2}" *)

module LFE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src,
        src_ap_vld,
        dst,
        dst_ap_vld,
        src_o,
        dst_o,
        cnt_i,
        cnt_o,
        cnt_o_ap_vld,
        cnt_o_ap_lwr
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] src;
input   src_ap_vld;
input  [31:0] dst;
input   dst_ap_vld;
input  [31:0] src_o;
input  [31:0] dst_o;
input  [31:0] cnt_i;
output  [31:0] cnt_o;
output   cnt_o_ap_vld;
output   cnt_o_ap_lwr;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg cnt_o_ap_vld;
reg cnt_o_ap_lwr;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
reg   [31:0] src_preg;
reg  signed [31:0] src_in_sig;
reg    src_ap_vld_preg;
reg    src_ap_vld_in_sig;
reg   [14:0] CM0_address0;
reg    CM0_ce0;
reg    CM0_we0;
wire   [31:0] CM0_q0;
reg   [14:0] CM1_address0;
reg    CM1_ce0;
reg    CM1_we0;
wire   [31:0] CM1_q0;
reg   [14:0] CM2_address0;
reg    CM2_ce0;
reg    CM2_we0;
wire   [31:0] CM2_q0;
reg   [14:0] CM3_address0;
reg    CM3_ce0;
reg    CM3_we0;
wire   [31:0] CM3_q0;
reg   [31:0] fifo_wr;
reg    src_blk_n;
wire    ap_block_pp0_stage0;
wire   [31:0] or_ln4_fu_255_p3;
reg   [31:0] or_ln4_reg_954;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] h1_1_fu_281_p2;
reg   [31:0] h1_1_reg_960;
wire   [31:0] h1_5_fu_305_p2;
reg   [31:0] h1_5_reg_965;
wire   [14:0] i0_fu_386_p2;
reg   [14:0] i0_reg_970;
wire   [14:0] i1_fu_467_p2;
reg   [14:0] i1_reg_975;
wire  signed [30:0] xor_ln11_2_fu_546_p2;
reg  signed [30:0] xor_ln11_2_reg_980;
wire  signed [30:0] xor_ln11_3_fu_625_p2;
reg  signed [30:0] xor_ln11_3_reg_985;
reg   [14:0] CM0_addr_reg_990;
reg   [14:0] CM1_addr_reg_995;
reg   [14:0] CM2_addr_reg_1000;
reg   [14:0] CM3_addr_reg_1005;
wire   [31:0] minv_5_fu_810_p3;
reg   [31:0] minv_5_reg_1010;
wire   [0:0] icmp_ln194_fu_824_p2;
reg   [0:0] icmp_ln194_reg_1015;
reg   [30:0] trunc_ln5_reg_1020;
wire   [30:0] result_1_fu_890_p3;
reg   [30:0] result_1_reg_1026;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln129_fu_688_p1;
wire   [63:0] zext_ln130_fu_692_p1;
wire   [63:0] zext_ln131_fu_696_p1;
wire   [63:0] zext_ln132_fu_701_p1;
wire   [31:0] select_ln254_fu_940_p3;
wire   [0:0] icmp_ln277_fu_918_p2;
wire    ap_block_pp0_stage1_01001;
wire   [31:0] c0_fu_706_p2;
wire    ap_block_pp0_stage1;
wire   [31:0] c1_fu_713_p2;
wire   [31:0] c2_fu_720_p2;
wire   [31:0] c3_fu_727_p2;
wire  signed [30:0] k1_1_fu_183_p1;
wire   [29:0] mul_ln4_fu_189_p1;
wire   [31:0] k1_1_fu_183_p2;
wire   [31:0] mul_ln4_fu_189_p2;
wire   [16:0] tmp_1_fu_205_p4;
wire   [14:0] lshr_ln4_fu_195_p4;
wire  signed [31:0] k1_fu_215_p3;
wire   [29:0] k1_2_fu_223_p1;
wire  signed [29:0] mul_ln4_1_fu_229_p1;
wire   [31:0] k1_2_fu_223_p2;
wire   [31:0] mul_ln4_1_fu_229_p2;
wire   [18:0] tmp_3_fu_245_p4;
wire   [12:0] lshr_ln4_1_fu_235_p4;
wire   [31:0] h1_fu_263_p2;
wire   [31:0] add_ln34_fu_275_p2;
wire   [31:0] shl_ln34_fu_269_p2;
wire   [31:0] h1_4_fu_287_p2;
wire   [31:0] add_ln34_2_fu_299_p2;
wire   [31:0] shl_ln34_1_fu_293_p2;
wire   [31:0] h1_2_fu_311_p2;
wire   [15:0] lshr_ln9_fu_316_p4;
wire   [31:0] zext_ln9_fu_326_p1;
wire  signed [31:0] mul_ln10_fu_336_p0;
wire   [31:0] mul_ln10_fu_336_p2;
wire   [18:0] trunc_ln_fu_346_p4;
wire   [30:0] zext_ln11_fu_356_p1;
wire   [30:0] trunc_ln7_fu_342_p1;
wire  signed [30:0] mul_ln12_fu_366_p0;
wire   [30:0] mul_ln12_fu_366_p2;
wire   [14:0] trunc_ln1_fu_376_p4;
wire   [14:0] trunc_ln7_1_fu_372_p1;
wire   [31:0] h1_6_fu_392_p2;
wire   [15:0] lshr_ln9_1_fu_397_p4;
wire   [31:0] zext_ln9_1_fu_407_p1;
wire  signed [31:0] mul_ln10_1_fu_417_p0;
wire   [31:0] mul_ln10_1_fu_417_p2;
wire   [18:0] trunc_ln11_1_fu_427_p4;
wire   [30:0] zext_ln11_1_fu_437_p1;
wire   [30:0] trunc_ln7_2_fu_423_p1;
wire  signed [30:0] mul_ln12_1_fu_447_p0;
wire   [30:0] mul_ln12_1_fu_447_p2;
wire   [14:0] trunc_ln13_1_fu_457_p4;
wire   [14:0] trunc_ln7_3_fu_453_p1;
wire   [31:0] h1_9_fu_473_p2;
wire   [31:0] add_ln34_4_fu_484_p2;
wire   [31:0] shl_ln34_2_fu_478_p2;
wire   [31:0] h1_10_fu_490_p2;
wire   [31:0] h1_11_fu_496_p2;
wire   [15:0] lshr_ln9_2_fu_502_p4;
wire   [31:0] zext_ln9_2_fu_512_p1;
wire  signed [31:0] mul_ln10_2_fu_522_p0;
wire   [31:0] mul_ln10_2_fu_522_p2;
wire   [18:0] trunc_ln11_2_fu_532_p4;
wire   [30:0] zext_ln11_2_fu_542_p1;
wire   [30:0] trunc_ln7_4_fu_528_p1;
wire   [31:0] h1_13_fu_552_p2;
wire   [31:0] add_ln34_6_fu_563_p2;
wire   [31:0] shl_ln34_3_fu_557_p2;
wire   [31:0] h1_14_fu_569_p2;
wire   [31:0] h1_15_fu_575_p2;
wire   [15:0] lshr_ln9_3_fu_581_p4;
wire   [31:0] zext_ln9_3_fu_591_p1;
wire  signed [31:0] mul_ln10_3_fu_601_p0;
wire   [31:0] mul_ln10_3_fu_601_p2;
wire   [18:0] trunc_ln11_3_fu_611_p4;
wire   [30:0] zext_ln11_3_fu_621_p1;
wire   [30:0] trunc_ln7_6_fu_607_p1;
wire   [30:0] mul_ln12_2_fu_638_p2;
wire   [14:0] trunc_ln13_2_fu_647_p4;
wire   [14:0] trunc_ln7_5_fu_643_p1;
wire   [30:0] mul_ln12_3_fu_663_p2;
wire   [14:0] trunc_ln13_3_fu_672_p4;
wire   [14:0] trunc_ln7_7_fu_668_p1;
wire   [14:0] i2_fu_657_p2;
wire   [14:0] i3_fu_682_p2;
wire   [0:0] icmp_ln168_fu_734_p2;
wire   [31:0] maxv_fu_740_p3;
wire   [0:0] icmp_ln171_fu_748_p2;
wire   [31:0] maxv_3_fu_754_p3;
wire   [0:0] icmp_ln174_fu_762_p2;
wire   [0:0] icmp_ln179_fu_776_p2;
wire   [31:0] minv_2_fu_782_p3;
wire   [0:0] icmp_ln182_fu_790_p2;
wire   [31:0] minv_3_fu_796_p3;
wire   [0:0] icmp_ln185_fu_804_p2;
wire   [31:0] maxv_4_fu_768_p3;
wire   [31:0] diff_fu_818_p2;
wire   [30:0] trunc_ln3_fu_840_p4;
wire   [30:0] trunc_ln2_fu_830_p4;
wire   [0:0] icmp_ln207_fu_870_p2;
wire   [30:0] trunc_ln4_fu_850_p4;
wire   [30:0] result_fu_876_p3;
wire   [0:0] icmp_ln210_fu_884_p2;
wire   [0:0] icmp_ln213_fu_898_p2;
wire   [30:0] result_2_fu_902_p3;
wire   [31:0] zext_ln204_fu_908_p1;
wire   [31:0] estimate_fu_912_p3;
wire   [31:0] add_ln252_fu_928_p2;
wire   [0:0] icmp_ln254_fu_934_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to2;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 src_preg = 32'd0;
#0 src_ap_vld_preg = 1'b0;
#0 fifo_wr = 32'd0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

LFE_CM0 #(
    .DataWidth( 32 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
CM0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CM0_address0),
    .ce0(CM0_ce0),
    .we0(CM0_we0),
    .d0(c0_fu_706_p2),
    .q0(CM0_q0)
);

LFE_CM0 #(
    .DataWidth( 32 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
CM1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CM1_address0),
    .ce0(CM1_ce0),
    .we0(CM1_we0),
    .d0(c1_fu_713_p2),
    .q0(CM1_q0)
);

LFE_CM0 #(
    .DataWidth( 32 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
CM2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CM2_address0),
    .ce0(CM2_ce0),
    .we0(CM2_we0),
    .d0(c2_fu_720_p2),
    .q0(CM2_q0)
);

LFE_CM0 #(
    .DataWidth( 32 ),
    .AddressRange( 32768 ),
    .AddressWidth( 15 ))
CM3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(CM3_address0),
    .ce0(CM3_ce0),
    .we0(CM3_we0),
    .d0(c3_fu_727_p2),
    .q0(CM3_q0)
);

LFE_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U1(
    .din0(src_in_sig),
    .din1(k1_1_fu_183_p1),
    .dout(k1_1_fu_183_p2)
);

LFE_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U2(
    .din0(src_in_sig),
    .din1(mul_ln4_fu_189_p1),
    .dout(mul_ln4_fu_189_p2)
);

LFE_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U3(
    .din0(k1_fu_215_p3),
    .din1(k1_2_fu_223_p1),
    .dout(k1_2_fu_223_p2)
);

LFE_mul_32s_30s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30s_32_1_1_U4(
    .din0(k1_fu_215_p3),
    .din1(mul_ln4_1_fu_229_p1),
    .dout(mul_ln4_1_fu_229_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U5(
    .din0(mul_ln10_fu_336_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_fu_336_p2)
);

LFE_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U6(
    .din0(mul_ln12_fu_366_p0),
    .din1(31'd1119006261),
    .dout(mul_ln12_fu_366_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U7(
    .din0(mul_ln10_1_fu_417_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_1_fu_417_p2)
);

LFE_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U8(
    .din0(mul_ln12_1_fu_447_p0),
    .din1(31'd1119006261),
    .dout(mul_ln12_1_fu_447_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U9(
    .din0(mul_ln10_2_fu_522_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_2_fu_522_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U10(
    .din0(mul_ln10_3_fu_601_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_3_fu_601_p2)
);

LFE_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U11(
    .din0(xor_ln11_2_reg_980),
    .din1(31'd1119006261),
    .dout(mul_ln12_2_fu_638_p2)
);

LFE_mul_31s_31s_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mul_31s_31s_31_1_1_U12(
    .din0(xor_ln11_3_reg_985),
    .din1(31'd1119006261),
    .dout(mul_ln12_3_fu_663_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        src_ap_vld_preg <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            src_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (src_ap_vld == 1'b1))) begin
            src_ap_vld_preg <= src_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        src_preg <= 32'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0)) & (src_ap_vld == 1'b1))) begin
            src_preg <= src;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        CM0_addr_reg_990 <= zext_ln129_fu_688_p1;
        CM1_addr_reg_995 <= zext_ln130_fu_692_p1;
        CM2_addr_reg_1000 <= zext_ln131_fu_696_p1;
        CM3_addr_reg_1005 <= zext_ln132_fu_701_p1;
        h1_1_reg_960 <= h1_1_fu_281_p2;
        h1_5_reg_965 <= h1_5_fu_305_p2;
        or_ln4_reg_954 <= or_ln4_fu_255_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln277_fu_918_p2 == 1'd0))) begin
        fifo_wr <= select_ln254_fu_940_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        i0_reg_970 <= i0_fu_386_p2;
        i1_reg_975 <= i1_fu_467_p2;
        icmp_ln194_reg_1015 <= icmp_ln194_fu_824_p2;
        minv_5_reg_1010 <= minv_5_fu_810_p3;
        result_1_reg_1026 <= result_1_fu_890_p3;
        trunc_ln5_reg_1020 <= {{c3_fu_727_p2[31:1]}};
        xor_ln11_2_reg_980 <= xor_ln11_2_fu_546_p2;
        xor_ln11_3_reg_985 <= xor_ln11_3_fu_625_p2;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            CM0_address0 = CM0_addr_reg_990;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            CM0_address0 = zext_ln129_fu_688_p1;
        end else begin
            CM0_address0 = 'bx;
        end
    end else begin
        CM0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        CM0_ce0 = 1'b1;
    end else begin
        CM0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        CM0_we0 = 1'b1;
    end else begin
        CM0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            CM1_address0 = CM1_addr_reg_995;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            CM1_address0 = zext_ln130_fu_692_p1;
        end else begin
            CM1_address0 = 'bx;
        end
    end else begin
        CM1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        CM1_ce0 = 1'b1;
    end else begin
        CM1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        CM1_we0 = 1'b1;
    end else begin
        CM1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            CM2_address0 = CM2_addr_reg_1000;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            CM2_address0 = zext_ln131_fu_696_p1;
        end else begin
            CM2_address0 = 'bx;
        end
    end else begin
        CM2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        CM2_ce0 = 1'b1;
    end else begin
        CM2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        CM2_we0 = 1'b1;
    end else begin
        CM2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            CM3_address0 = CM3_addr_reg_1005;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            CM3_address0 = zext_ln132_fu_701_p1;
        end else begin
            CM3_address0 = 'bx;
        end
    end else begin
        CM3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        CM3_ce0 = 1'b1;
    end else begin
        CM3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        CM3_we0 = 1'b1;
    end else begin
        CM3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_o_ap_lwr = 1'b1;
    end else begin
        cnt_o_ap_lwr = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_o_ap_vld = 1'b1;
    end else begin
        cnt_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((src_ap_vld == 1'b1)) begin
        src_ap_vld_in_sig = src_ap_vld;
    end else begin
        src_ap_vld_in_sig = src_ap_vld_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_blk_n = src_ap_vld;
    end else begin
        src_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((src_ap_vld == 1'b1)) begin
        src_in_sig = src;
    end else begin
        src_in_sig = src_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (ap_reset_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln252_fu_928_p2 = (fifo_wr + 32'd1);

assign add_ln34_2_fu_299_p2 = ($signed(h1_4_fu_287_p2) + $signed(32'd3864292196));

assign add_ln34_4_fu_484_p2 = ($signed(h1_9_fu_473_p2) + $signed(32'd3864292196));

assign add_ln34_6_fu_563_p2 = ($signed(h1_13_fu_552_p2) + $signed(32'd3864292196));

assign add_ln34_fu_275_p2 = ($signed(h1_fu_263_p2) + $signed(32'd3864292196));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((src_ap_vld_in_sig == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((src_ap_vld_in_sig == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (src_ap_vld_in_sig == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign c0_fu_706_p2 = (CM0_q0 + 32'd1);

assign c1_fu_713_p2 = (CM1_q0 + 32'd1);

assign c2_fu_720_p2 = (CM2_q0 + 32'd1);

assign c3_fu_727_p2 = (CM3_q0 + 32'd1);

assign cnt_o = (cnt_i + 32'd1);

assign diff_fu_818_p2 = (maxv_4_fu_768_p3 - minv_5_fu_810_p3);

assign estimate_fu_912_p3 = ((icmp_ln194_reg_1015[0:0] == 1'b1) ? zext_ln204_fu_908_p1 : minv_5_reg_1010);

assign h1_10_fu_490_p2 = (add_ln34_4_fu_484_p2 + shl_ln34_2_fu_478_p2);

assign h1_11_fu_496_p2 = (h1_10_fu_490_p2 ^ 32'd4);

assign h1_13_fu_552_p2 = (or_ln4_reg_954 ^ 32'd32768);

assign h1_14_fu_569_p2 = (add_ln34_6_fu_563_p2 + shl_ln34_3_fu_557_p2);

assign h1_15_fu_575_p2 = (h1_14_fu_569_p2 ^ 32'd4);

assign h1_1_fu_281_p2 = (add_ln34_fu_275_p2 + shl_ln34_fu_269_p2);

assign h1_2_fu_311_p2 = (h1_1_reg_960 ^ 32'd4);

assign h1_4_fu_287_p2 = (or_ln4_fu_255_p3 ^ 32'd16384);

assign h1_5_fu_305_p2 = (add_ln34_2_fu_299_p2 + shl_ln34_1_fu_293_p2);

assign h1_6_fu_392_p2 = (h1_5_reg_965 ^ 32'd4);

assign h1_9_fu_473_p2 = (or_ln4_reg_954 ^ 32'd24576);

assign h1_fu_263_p2 = (or_ln4_fu_255_p3 ^ 32'd8192);

assign i0_fu_386_p2 = (trunc_ln7_1_fu_372_p1 ^ trunc_ln1_fu_376_p4);

assign i1_fu_467_p2 = (trunc_ln7_3_fu_453_p1 ^ trunc_ln13_1_fu_457_p4);

assign i2_fu_657_p2 = (trunc_ln7_5_fu_643_p1 ^ trunc_ln13_2_fu_647_p4);

assign i3_fu_682_p2 = (trunc_ln7_7_fu_668_p1 ^ trunc_ln13_3_fu_672_p4);

assign icmp_ln168_fu_734_p2 = ((c1_fu_713_p2 > c0_fu_706_p2) ? 1'b1 : 1'b0);

assign icmp_ln171_fu_748_p2 = ((c2_fu_720_p2 > maxv_fu_740_p3) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_762_p2 = ((c3_fu_727_p2 > maxv_3_fu_754_p3) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_776_p2 = ((c1_fu_713_p2 < c0_fu_706_p2) ? 1'b1 : 1'b0);

assign icmp_ln182_fu_790_p2 = ((c2_fu_720_p2 < minv_2_fu_782_p3) ? 1'b1 : 1'b0);

assign icmp_ln185_fu_804_p2 = ((c3_fu_727_p2 < minv_3_fu_796_p3) ? 1'b1 : 1'b0);

assign icmp_ln194_fu_824_p2 = ((diff_fu_818_p2 > 32'd3000) ? 1'b1 : 1'b0);

assign icmp_ln207_fu_870_p2 = ((trunc_ln3_fu_840_p4 < trunc_ln2_fu_830_p4) ? 1'b1 : 1'b0);

assign icmp_ln210_fu_884_p2 = ((trunc_ln4_fu_850_p4 < result_fu_876_p3) ? 1'b1 : 1'b0);

assign icmp_ln213_fu_898_p2 = ((trunc_ln5_reg_1020 < result_1_reg_1026) ? 1'b1 : 1'b0);

assign icmp_ln254_fu_934_p2 = ((add_ln252_fu_928_p2 == 32'd256) ? 1'b1 : 1'b0);

assign icmp_ln277_fu_918_p2 = ((estimate_fu_912_p3 == 32'd0) ? 1'b1 : 1'b0);

assign k1_1_fu_183_p1 = 32'd3432918353;

assign k1_2_fu_223_p1 = 32'd461845907;

assign k1_fu_215_p3 = {{tmp_1_fu_205_p4}, {lshr_ln4_fu_195_p4}};

assign lshr_ln4_1_fu_235_p4 = {{k1_2_fu_223_p2[31:19]}};

assign lshr_ln4_fu_195_p4 = {{k1_1_fu_183_p2[31:17]}};

assign lshr_ln9_1_fu_397_p4 = {{h1_6_fu_392_p2[31:16]}};

assign lshr_ln9_2_fu_502_p4 = {{h1_11_fu_496_p2[31:16]}};

assign lshr_ln9_3_fu_581_p4 = {{h1_15_fu_575_p2[31:16]}};

assign lshr_ln9_fu_316_p4 = {{h1_2_fu_311_p2[31:16]}};

assign maxv_3_fu_754_p3 = ((icmp_ln171_fu_748_p2[0:0] == 1'b1) ? c2_fu_720_p2 : maxv_fu_740_p3);

assign maxv_4_fu_768_p3 = ((icmp_ln174_fu_762_p2[0:0] == 1'b1) ? c3_fu_727_p2 : maxv_3_fu_754_p3);

assign maxv_fu_740_p3 = ((icmp_ln168_fu_734_p2[0:0] == 1'b1) ? c1_fu_713_p2 : c0_fu_706_p2);

assign minv_2_fu_782_p3 = ((icmp_ln179_fu_776_p2[0:0] == 1'b1) ? c1_fu_713_p2 : c0_fu_706_p2);

assign minv_3_fu_796_p3 = ((icmp_ln182_fu_790_p2[0:0] == 1'b1) ? c2_fu_720_p2 : minv_2_fu_782_p3);

assign minv_5_fu_810_p3 = ((icmp_ln185_fu_804_p2[0:0] == 1'b1) ? c3_fu_727_p2 : minv_3_fu_796_p3);

assign mul_ln10_1_fu_417_p0 = (zext_ln9_1_fu_407_p1 ^ h1_6_fu_392_p2);

assign mul_ln10_2_fu_522_p0 = (zext_ln9_2_fu_512_p1 ^ h1_11_fu_496_p2);

assign mul_ln10_3_fu_601_p0 = (zext_ln9_3_fu_591_p1 ^ h1_15_fu_575_p2);

assign mul_ln10_fu_336_p0 = (zext_ln9_fu_326_p1 ^ h1_2_fu_311_p2);

assign mul_ln12_1_fu_447_p0 = (zext_ln11_1_fu_437_p1 ^ trunc_ln7_2_fu_423_p1);

assign mul_ln12_fu_366_p0 = (zext_ln11_fu_356_p1 ^ trunc_ln7_fu_342_p1);

assign mul_ln4_1_fu_229_p1 = 32'd3870449664;

assign mul_ln4_fu_189_p1 = 32'd380141568;

assign or_ln4_fu_255_p3 = {{tmp_3_fu_245_p4}, {lshr_ln4_1_fu_235_p4}};

assign result_1_fu_890_p3 = ((icmp_ln210_fu_884_p2[0:0] == 1'b1) ? trunc_ln4_fu_850_p4 : result_fu_876_p3);

assign result_2_fu_902_p3 = ((icmp_ln213_fu_898_p2[0:0] == 1'b1) ? trunc_ln5_reg_1020 : result_1_reg_1026);

assign result_fu_876_p3 = ((icmp_ln207_fu_870_p2[0:0] == 1'b1) ? trunc_ln3_fu_840_p4 : trunc_ln2_fu_830_p4);

assign select_ln254_fu_940_p3 = ((icmp_ln254_fu_934_p2[0:0] == 1'b1) ? 32'd0 : add_ln252_fu_928_p2);

assign shl_ln34_1_fu_293_p2 = h1_4_fu_287_p2 << 32'd2;

assign shl_ln34_2_fu_478_p2 = h1_9_fu_473_p2 << 32'd2;

assign shl_ln34_3_fu_557_p2 = h1_13_fu_552_p2 << 32'd2;

assign shl_ln34_fu_269_p2 = h1_fu_263_p2 << 32'd2;

assign tmp_1_fu_205_p4 = {{mul_ln4_fu_189_p2[31:15]}};

assign tmp_3_fu_245_p4 = {{mul_ln4_1_fu_229_p2[31:13]}};

assign trunc_ln11_1_fu_427_p4 = {{mul_ln10_1_fu_417_p2[31:13]}};

assign trunc_ln11_2_fu_532_p4 = {{mul_ln10_2_fu_522_p2[31:13]}};

assign trunc_ln11_3_fu_611_p4 = {{mul_ln10_3_fu_601_p2[31:13]}};

assign trunc_ln13_1_fu_457_p4 = {{mul_ln12_1_fu_447_p2[30:16]}};

assign trunc_ln13_2_fu_647_p4 = {{mul_ln12_2_fu_638_p2[30:16]}};

assign trunc_ln13_3_fu_672_p4 = {{mul_ln12_3_fu_663_p2[30:16]}};

assign trunc_ln1_fu_376_p4 = {{mul_ln12_fu_366_p2[30:16]}};

assign trunc_ln2_fu_830_p4 = {{c0_fu_706_p2[31:1]}};

assign trunc_ln3_fu_840_p4 = {{c1_fu_713_p2[31:1]}};

assign trunc_ln4_fu_850_p4 = {{c2_fu_720_p2[31:1]}};

assign trunc_ln7_1_fu_372_p1 = mul_ln12_fu_366_p2[14:0];

assign trunc_ln7_2_fu_423_p1 = mul_ln10_1_fu_417_p2[30:0];

assign trunc_ln7_3_fu_453_p1 = mul_ln12_1_fu_447_p2[14:0];

assign trunc_ln7_4_fu_528_p1 = mul_ln10_2_fu_522_p2[30:0];

assign trunc_ln7_5_fu_643_p1 = mul_ln12_2_fu_638_p2[14:0];

assign trunc_ln7_6_fu_607_p1 = mul_ln10_3_fu_601_p2[30:0];

assign trunc_ln7_7_fu_668_p1 = mul_ln12_3_fu_663_p2[14:0];

assign trunc_ln7_fu_342_p1 = mul_ln10_fu_336_p2[30:0];

assign trunc_ln_fu_346_p4 = {{mul_ln10_fu_336_p2[31:13]}};

assign xor_ln11_2_fu_546_p2 = (zext_ln11_2_fu_542_p1 ^ trunc_ln7_4_fu_528_p1);

assign xor_ln11_3_fu_625_p2 = (zext_ln11_3_fu_621_p1 ^ trunc_ln7_6_fu_607_p1);

assign zext_ln11_1_fu_437_p1 = trunc_ln11_1_fu_427_p4;

assign zext_ln11_2_fu_542_p1 = trunc_ln11_2_fu_532_p4;

assign zext_ln11_3_fu_621_p1 = trunc_ln11_3_fu_611_p4;

assign zext_ln11_fu_356_p1 = trunc_ln_fu_346_p4;

assign zext_ln129_fu_688_p1 = i0_reg_970;

assign zext_ln130_fu_692_p1 = i1_reg_975;

assign zext_ln131_fu_696_p1 = i2_fu_657_p2;

assign zext_ln132_fu_701_p1 = i3_fu_682_p2;

assign zext_ln204_fu_908_p1 = result_2_fu_902_p3;

assign zext_ln9_1_fu_407_p1 = lshr_ln9_1_fu_397_p4;

assign zext_ln9_2_fu_512_p1 = lshr_ln9_2_fu_502_p4;

assign zext_ln9_3_fu_591_p1 = lshr_ln9_3_fu_581_p4;

assign zext_ln9_fu_326_p1 = lshr_ln9_fu_316_p4;

endmodule //LFE
