// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module topk_MurmurHash3_x86_32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_read;
output  [9:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] h1_16_fu_158_p2;
reg   [31:0] h1_16_reg_245;
wire  signed [30:0] k1_3_fu_60_p1;
wire   [29:0] mul_ln5_fu_66_p1;
wire   [31:0] k1_3_fu_60_p2;
wire   [31:0] mul_ln5_fu_66_p2;
wire   [16:0] tmp_s_fu_82_p4;
wire   [14:0] lshr_ln5_fu_72_p4;
wire  signed [31:0] k1_fu_92_p3;
wire   [29:0] k1_4_fu_100_p1;
wire  signed [29:0] mul_ln5_2_fu_106_p1;
wire   [31:0] k1_4_fu_100_p2;
wire   [31:0] mul_ln5_2_fu_106_p2;
wire   [18:0] tmp_14_fu_122_p4;
wire   [12:0] lshr_ln5_2_fu_112_p4;
wire   [31:0] or_ln5_fu_132_p3;
wire   [31:0] h1_fu_140_p2;
wire   [31:0] add_ln37_fu_152_p2;
wire   [31:0] shl_ln37_fu_146_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] h1_17_fu_164_p2;
wire   [15:0] lshr_ln_fu_169_p4;
wire   [31:0] zext_ln10_fu_179_p1;
wire  signed [31:0] mul_ln11_fu_189_p0;
wire   [31:0] mul_ln11_fu_189_p2;
wire   [18:0] tmp_15_fu_199_p4;
wire   [25:0] zext_ln12_fu_209_p1;
wire   [25:0] trunc_ln8_fu_195_p1;
wire  signed [25:0] mul_ln13_fu_219_p0;
wire   [25:0] mul_ln13_fu_219_p2;
wire   [9:0] trunc_ln_fu_229_p4;
wire   [9:0] trunc_ln8_1_fu_225_p1;
reg   [1:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
end

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U30(
    .din0(p_read),
    .din1(k1_3_fu_60_p1),
    .dout(k1_3_fu_60_p2)
);

topk_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U31(
    .din0(p_read),
    .din1(mul_ln5_fu_66_p1),
    .dout(mul_ln5_fu_66_p2)
);

topk_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U32(
    .din0(k1_fu_92_p3),
    .din1(k1_4_fu_100_p1),
    .dout(k1_4_fu_100_p2)
);

topk_mul_32s_30s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30s_32_1_1_U33(
    .din0(k1_fu_92_p3),
    .din1(mul_ln5_2_fu_106_p1),
    .dout(mul_ln5_2_fu_106_p2)
);

topk_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U34(
    .din0(mul_ln11_fu_189_p0),
    .din1(32'd2246822507),
    .dout(mul_ln11_fu_189_p2)
);

topk_mul_26s_26s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 26 ))
mul_26s_26s_26_1_1_U35(
    .din0(mul_ln13_fu_219_p0),
    .din1(26'd45264437),
    .dout(mul_ln13_fu_219_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        h1_16_reg_245 <= h1_16_fu_158_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_152_p2 = ($signed(h1_fu_140_p2) + $signed(32'd3864292196));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_return = (trunc_ln_fu_229_p4 ^ trunc_ln8_1_fu_225_p1);

assign h1_16_fu_158_p2 = (add_ln37_fu_152_p2 + shl_ln37_fu_146_p2);

assign h1_17_fu_164_p2 = (h1_16_reg_245 ^ 32'd4);

assign h1_fu_140_p2 = (or_ln5_fu_132_p3 ^ 32'd73728);

assign k1_3_fu_60_p1 = 32'd3432918353;

assign k1_4_fu_100_p1 = 32'd461845907;

assign k1_fu_92_p3 = {{tmp_s_fu_82_p4}, {lshr_ln5_fu_72_p4}};

assign lshr_ln5_2_fu_112_p4 = {{k1_4_fu_100_p2[31:19]}};

assign lshr_ln5_fu_72_p4 = {{k1_3_fu_60_p2[31:17]}};

assign lshr_ln_fu_169_p4 = {{h1_17_fu_164_p2[31:16]}};

assign mul_ln11_fu_189_p0 = (zext_ln10_fu_179_p1 ^ h1_17_fu_164_p2);

assign mul_ln13_fu_219_p0 = (zext_ln12_fu_209_p1 ^ trunc_ln8_fu_195_p1);

assign mul_ln5_2_fu_106_p1 = 32'd3870449664;

assign mul_ln5_fu_66_p1 = 32'd380141568;

assign or_ln5_fu_132_p3 = {{tmp_14_fu_122_p4}, {lshr_ln5_2_fu_112_p4}};

assign shl_ln37_fu_146_p2 = h1_fu_140_p2 << 32'd2;

assign tmp_14_fu_122_p4 = {{mul_ln5_2_fu_106_p2[31:13]}};

assign tmp_15_fu_199_p4 = {{mul_ln11_fu_189_p2[31:13]}};

assign tmp_s_fu_82_p4 = {{mul_ln5_fu_66_p2[31:15]}};

assign trunc_ln8_1_fu_225_p1 = mul_ln13_fu_219_p2[9:0];

assign trunc_ln8_fu_195_p1 = mul_ln11_fu_189_p2[25:0];

assign trunc_ln_fu_229_p4 = {{mul_ln13_fu_219_p2[25:16]}};

assign zext_ln10_fu_179_p1 = lshr_ln_fu_169_p4;

assign zext_ln12_fu_209_p1 = tmp_15_fu_199_p4;

endmodule //topk_MurmurHash3_x86_32
