// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module topk_cm_stage (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        candidate_stream_din,
        candidate_stream_full_n,
        candidate_stream_write,
        start_out,
        start_write,
        key_dout,
        key_empty_n,
        key_read,
        valid_dout,
        valid_empty_n,
        valid_read
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [63:0] candidate_stream_din;
input   candidate_stream_full_n;
output   candidate_stream_write;
output   start_out;
output   start_write;
input  [31:0] key_dout;
input   key_empty_n;
output   key_read;
input  [0:0] valid_dout;
input   valid_empty_n;
output   valid_read;

reg ap_done;
reg ap_idle;
reg candidate_stream_write;
reg start_write;
reg key_read;
reg valid_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_idle_pp0;
reg    internal_ap_ready;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_state14_pp0_stage1_iter6;
wire    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
wire    ap_block_state22_pp0_stage1_iter10;
wire    ap_block_state24_pp0_stage1_iter11;
wire    ap_block_state26_pp0_stage1_iter12;
wire    ap_block_state28_pp0_stage1_iter13;
wire    ap_block_state30_pp0_stage1_iter14;
wire    ap_block_state32_pp0_stage1_iter15;
wire    ap_block_state34_pp0_stage1_iter16;
wire    ap_block_state36_pp0_stage1_iter17;
wire    ap_block_state38_pp0_stage1_iter18;
wire    ap_block_state40_pp0_stage1_iter19;
reg   [0:0] valid_read_reg_919;
reg   [0:0] valid_read_reg_919_pp0_iter20_reg;
reg    ap_block_state42_pp0_stage1_iter20;
reg    ap_block_pp0_stage1_11001;
reg   [13:0] cm0_address0;
reg    cm0_ce0;
reg    cm0_we0;
wire   [31:0] cm0_q0;
reg   [13:0] cm1_address0;
reg    cm1_ce0;
reg    cm1_we0;
wire   [31:0] cm1_q0;
reg   [13:0] cm2_address0;
reg    cm2_ce0;
reg    cm2_we0;
wire   [31:0] cm2_q0;
reg   [13:0] cm3_address0;
reg    cm3_ce0;
reg    cm3_we0;
wire   [31:0] cm3_q0;
reg    key_blk_n;
wire    ap_block_pp0_stage0;
reg    valid_blk_n;
reg    candidate_stream_blk_n;
wire    ap_block_pp0_stage1;
reg  signed [31:0] key_read_reg_914;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
wire    ap_block_state21_pp0_stage0_iter10;
wire    ap_block_state23_pp0_stage0_iter11;
wire    ap_block_state25_pp0_stage0_iter12;
wire    ap_block_state27_pp0_stage0_iter13;
wire    ap_block_state29_pp0_stage0_iter14;
wire    ap_block_state31_pp0_stage0_iter15;
wire    ap_block_state33_pp0_stage0_iter16;
wire    ap_block_state35_pp0_stage0_iter17;
wire    ap_block_state37_pp0_stage0_iter18;
wire    ap_block_state39_pp0_stage0_iter19;
wire    ap_block_state41_pp0_stage0_iter20;
reg    ap_block_pp0_stage0_11001;
reg  signed [31:0] key_read_reg_914_pp0_iter1_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter2_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter3_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter4_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter5_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter6_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter7_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter8_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter9_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter10_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter11_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter12_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter13_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter14_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter15_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter16_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter17_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter18_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter19_reg;
reg  signed [31:0] key_read_reg_914_pp0_iter20_reg;
wire   [0:0] valid_read_read_fu_114_p2;
reg   [0:0] valid_read_reg_919_pp0_iter1_reg;
reg   [0:0] valid_read_reg_919_pp0_iter2_reg;
reg   [0:0] valid_read_reg_919_pp0_iter3_reg;
reg   [0:0] valid_read_reg_919_pp0_iter4_reg;
reg   [0:0] valid_read_reg_919_pp0_iter5_reg;
reg   [0:0] valid_read_reg_919_pp0_iter6_reg;
reg   [0:0] valid_read_reg_919_pp0_iter7_reg;
reg   [0:0] valid_read_reg_919_pp0_iter8_reg;
reg   [0:0] valid_read_reg_919_pp0_iter9_reg;
reg   [0:0] valid_read_reg_919_pp0_iter10_reg;
reg   [0:0] valid_read_reg_919_pp0_iter11_reg;
reg   [0:0] valid_read_reg_919_pp0_iter12_reg;
reg   [0:0] valid_read_reg_919_pp0_iter13_reg;
reg   [0:0] valid_read_reg_919_pp0_iter14_reg;
reg   [0:0] valid_read_reg_919_pp0_iter15_reg;
reg   [0:0] valid_read_reg_919_pp0_iter16_reg;
reg   [0:0] valid_read_reg_919_pp0_iter17_reg;
reg   [0:0] valid_read_reg_919_pp0_iter18_reg;
reg   [0:0] valid_read_reg_919_pp0_iter19_reg;
reg   [14:0] lshr_ln5_i_reg_923;
reg   [16:0] tmp_16_i_reg_928;
wire   [31:0] or_ln5_i_fu_249_p3;
reg   [31:0] or_ln5_i_reg_933;
wire   [31:0] h1_1_fu_275_p2;
reg   [31:0] h1_1_reg_940;
wire   [31:0] out_fu_352_p2;
reg   [31:0] out_reg_945;
wire  signed [31:0] xor_ln12_1_fu_427_p2;
reg  signed [31:0] xor_ln12_1_reg_950;
wire  signed [31:0] xor_ln12_2_fu_502_p2;
reg  signed [31:0] xor_ln12_2_reg_955;
wire   [31:0] h1_13_fu_525_p2;
reg   [31:0] h1_13_reg_960;
wire   [31:0] out_7_fu_586_p2;
reg   [31:0] out_7_reg_970;
wire   [31:0] out_8_fu_663_p2;
reg   [31:0] out_8_reg_975;
reg   [13:0] cm0_addr_reg_980;
reg   [13:0] cm1_addr_reg_985;
reg   [13:0] cm2_addr_reg_990;
reg   [13:0] cm3_addr_reg_995;
wire   [31:0] c0_2_fu_699_p2;
reg   [31:0] c0_2_reg_1000;
wire   [31:0] c1_2_fu_706_p2;
reg   [31:0] c1_2_reg_1008;
wire   [30:0] est_1_fu_739_p3;
reg   [30:0] est_1_reg_1016;
wire   [31:0] est_fu_899_p3;
reg   [31:0] est_reg_1022;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage1_subdone;
wire   [63:0] zext_ln154_fu_679_p1;
wire   [63:0] zext_ln155_fu_684_p1;
wire   [63:0] zext_ln156_fu_689_p1;
wire   [63:0] zext_ln157_fu_694_p1;
reg    ap_block_pp0_stage1_01001;
wire   [31:0] c2_2_fu_747_p2;
wire   [31:0] c3_2_fu_754_p2;
wire  signed [30:0] k1_fu_179_p1;
wire   [29:0] mul_ln5_fu_185_p1;
wire   [31:0] k1_fu_179_p2;
wire   [31:0] mul_ln5_fu_185_p2;
wire  signed [31:0] k1_1_fu_211_p3;
wire   [29:0] k1_2_fu_217_p1;
wire  signed [29:0] mul_ln5_1_fu_223_p1;
wire   [31:0] k1_2_fu_217_p2;
wire   [31:0] mul_ln5_1_fu_223_p2;
wire   [18:0] tmp_18_i_fu_239_p4;
wire   [12:0] lshr_ln5_1_i_fu_229_p4;
wire   [31:0] h1_fu_257_p2;
wire   [31:0] add_ln37_fu_269_p2;
wire   [31:0] shl_ln37_fu_263_p2;
wire   [31:0] h1_2_fu_281_p2;
wire   [15:0] lshr_ln_i_fu_286_p4;
wire   [31:0] zext_ln10_fu_296_p1;
wire  signed [31:0] mul_ln11_fu_306_p0;
wire   [31:0] mul_ln11_fu_306_p2;
wire   [18:0] lshr_ln1_i_fu_312_p4;
wire   [31:0] zext_ln12_fu_322_p1;
wire  signed [31:0] mul_ln13_fu_332_p0;
wire  signed [30:0] mul_ln13_fu_332_p1;
wire   [31:0] mul_ln13_fu_332_p2;
wire   [15:0] lshr_ln2_i_fu_338_p4;
wire   [31:0] zext_ln14_fu_348_p1;
wire   [31:0] h1_4_fu_358_p2;
wire   [31:0] add_ln37_2_fu_369_p2;
wire   [31:0] shl_ln37_1_fu_363_p2;
wire   [31:0] h1_5_fu_375_p2;
wire   [31:0] h1_6_fu_381_p2;
wire   [15:0] lshr_ln10_1_i_fu_387_p4;
wire   [31:0] zext_ln10_1_fu_397_p1;
wire  signed [31:0] mul_ln11_1_fu_407_p0;
wire   [31:0] mul_ln11_1_fu_407_p2;
wire   [18:0] lshr_ln12_1_i_fu_413_p4;
wire   [31:0] zext_ln12_1_fu_423_p1;
wire   [31:0] h1_8_fu_433_p2;
wire   [31:0] add_ln37_4_fu_444_p2;
wire   [31:0] shl_ln37_2_fu_438_p2;
wire   [31:0] h1_9_fu_450_p2;
wire   [31:0] h1_10_fu_456_p2;
wire   [15:0] lshr_ln10_2_i_fu_462_p4;
wire   [31:0] zext_ln10_2_fu_472_p1;
wire  signed [31:0] mul_ln11_2_fu_482_p0;
wire   [31:0] mul_ln11_2_fu_482_p2;
wire   [18:0] lshr_ln12_2_i_fu_488_p4;
wire   [31:0] zext_ln12_2_fu_498_p1;
wire   [31:0] h1_12_fu_508_p2;
wire   [31:0] add_ln37_6_fu_519_p2;
wire   [31:0] shl_ln37_3_fu_513_p2;
wire   [14:0] grp_fu_531_p1;
wire  signed [30:0] mul_ln13_1_fu_536_p1;
wire   [31:0] mul_ln13_1_fu_536_p2;
wire   [15:0] lshr_ln14_1_i_fu_541_p4;
wire   [31:0] zext_ln14_1_fu_551_p1;
wire   [31:0] grp_fu_561_p0;
wire   [14:0] grp_fu_561_p1;
wire  signed [30:0] mul_ln13_2_fu_567_p1;
wire   [31:0] mul_ln13_2_fu_567_p2;
wire   [15:0] lshr_ln14_2_i_fu_572_p4;
wire   [31:0] zext_ln14_2_fu_582_p1;
wire   [31:0] h1_14_fu_592_p2;
wire   [15:0] lshr_ln10_3_i_fu_597_p4;
wire   [31:0] zext_ln10_3_fu_607_p1;
wire  signed [31:0] mul_ln11_3_fu_617_p0;
wire   [31:0] mul_ln11_3_fu_617_p2;
wire   [18:0] lshr_ln12_3_i_fu_623_p4;
wire   [31:0] zext_ln12_3_fu_633_p1;
wire  signed [31:0] mul_ln13_3_fu_643_p0;
wire  signed [30:0] mul_ln13_3_fu_643_p1;
wire   [31:0] mul_ln13_3_fu_643_p2;
wire   [15:0] lshr_ln14_3_i_fu_649_p4;
wire   [31:0] zext_ln14_3_fu_659_p1;
wire   [14:0] grp_fu_669_p1;
wire   [14:0] grp_fu_674_p1;
wire   [31:0] grp_fu_531_p2;
wire   [31:0] grp_fu_561_p2;
wire   [31:0] grp_fu_669_p2;
wire   [31:0] grp_fu_674_p2;
wire   [30:0] trunc_ln7_i_fu_723_p4;
wire   [30:0] trunc_ln_i_fu_713_p4;
wire   [0:0] icmp_ln208_fu_733_p2;
wire   [0:0] icmp_ln177_fu_761_p2;
wire   [31:0] maxv_fu_765_p3;
wire   [0:0] icmp_ln180_fu_771_p2;
wire   [31:0] maxv_2_fu_777_p3;
wire   [0:0] icmp_ln183_fu_785_p2;
wire   [0:0] icmp_ln187_fu_799_p2;
wire   [31:0] minv_2_fu_803_p3;
wire   [0:0] icmp_ln190_fu_809_p2;
wire   [31:0] minv_3_fu_815_p3;
wire   [0:0] icmp_ln193_fu_823_p2;
wire   [31:0] maxv_3_fu_791_p3;
wire   [31:0] minv_fu_829_p3;
wire   [31:0] sub_ln204_fu_837_p2;
wire   [30:0] trunc_ln8_i_fu_849_p4;
wire   [0:0] icmp_ln211_fu_859_p2;
wire   [30:0] trunc_ln9_i_fu_871_p4;
wire   [30:0] est_2_fu_864_p3;
wire   [0:0] icmp_ln214_fu_881_p2;
wire   [30:0] est_3_fu_887_p3;
wire   [0:0] icmp_ln204_fu_843_p2;
wire   [31:0] zext_ln197_fu_895_p1;
reg    grp_fu_531_ce;
reg    grp_fu_561_ce;
reg    grp_fu_669_ce;
reg    grp_fu_674_ce;
reg   [1:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to20;
reg    ap_idle_pp0_0to19;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

topk_cm_stage_cm0 #(
    .DataWidth( 32 ),
    .AddressRange( 14336 ),
    .AddressWidth( 14 ))
cm0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cm0_address0),
    .ce0(cm0_ce0),
    .we0(cm0_we0),
    .d0(c0_2_fu_699_p2),
    .q0(cm0_q0)
);

topk_cm_stage_cm0 #(
    .DataWidth( 32 ),
    .AddressRange( 14336 ),
    .AddressWidth( 14 ))
cm1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cm1_address0),
    .ce0(cm1_ce0),
    .we0(cm1_we0),
    .d0(c1_2_fu_706_p2),
    .q0(cm1_q0)
);

topk_cm_stage_cm0 #(
    .DataWidth( 32 ),
    .AddressRange( 14336 ),
    .AddressWidth( 14 ))
cm2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cm2_address0),
    .ce0(cm2_ce0),
    .we0(cm2_we0),
    .d0(c2_2_fu_747_p2),
    .q0(cm2_q0)
);

topk_cm_stage_cm0 #(
    .DataWidth( 32 ),
    .AddressRange( 14336 ),
    .AddressWidth( 14 ))
cm3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cm3_address0),
    .ce0(cm3_ce0),
    .we0(cm3_we0),
    .d0(c3_2_fu_754_p2),
    .q0(cm3_q0)
);

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U5(
    .din0(key_dout),
    .din1(k1_fu_179_p1),
    .dout(k1_fu_179_p2)
);

topk_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U6(
    .din0(key_dout),
    .din1(mul_ln5_fu_185_p1),
    .dout(mul_ln5_fu_185_p2)
);

topk_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U7(
    .din0(k1_1_fu_211_p3),
    .din1(k1_2_fu_217_p1),
    .dout(k1_2_fu_217_p2)
);

topk_mul_32s_30s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30s_32_1_1_U8(
    .din0(k1_1_fu_211_p3),
    .din1(mul_ln5_1_fu_223_p1),
    .dout(mul_ln5_1_fu_223_p2)
);

topk_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U9(
    .din0(mul_ln11_fu_306_p0),
    .din1(32'd2246822507),
    .dout(mul_ln11_fu_306_p2)
);

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U10(
    .din0(mul_ln13_fu_332_p0),
    .din1(mul_ln13_fu_332_p1),
    .dout(mul_ln13_fu_332_p2)
);

topk_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U11(
    .din0(mul_ln11_1_fu_407_p0),
    .din1(32'd2246822507),
    .dout(mul_ln11_1_fu_407_p2)
);

topk_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U12(
    .din0(mul_ln11_2_fu_482_p0),
    .din1(32'd2246822507),
    .dout(mul_ln11_2_fu_482_p2)
);

topk_urem_32ns_15ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
urem_32ns_15ns_32_36_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(out_reg_945),
    .din1(grp_fu_531_p1),
    .ce(grp_fu_531_ce),
    .dout(grp_fu_531_p2)
);

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U14(
    .din0(xor_ln12_1_reg_950),
    .din1(mul_ln13_1_fu_536_p1),
    .dout(mul_ln13_1_fu_536_p2)
);

topk_urem_32ns_15ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
urem_32ns_15ns_32_36_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_561_p0),
    .din1(grp_fu_561_p1),
    .ce(grp_fu_561_ce),
    .dout(grp_fu_561_p2)
);

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U16(
    .din0(xor_ln12_2_reg_955),
    .din1(mul_ln13_2_fu_567_p1),
    .dout(mul_ln13_2_fu_567_p2)
);

topk_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U17(
    .din0(mul_ln11_3_fu_617_p0),
    .din1(32'd2246822507),
    .dout(mul_ln11_3_fu_617_p2)
);

topk_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U18(
    .din0(mul_ln13_3_fu_643_p0),
    .din1(mul_ln13_3_fu_643_p1),
    .dout(mul_ln13_3_fu_643_p2)
);

topk_urem_32ns_15ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
urem_32ns_15ns_32_36_1_U19(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(out_7_reg_970),
    .din1(grp_fu_669_p1),
    .ce(grp_fu_669_ce),
    .dout(grp_fu_669_p2)
);

topk_urem_32ns_15ns_32_36_1 #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 32 ))
urem_32ns_15ns_32_36_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(out_8_reg_975),
    .din1(grp_fu_674_p1),
    .ce(grp_fu_674_ce),
    .dout(grp_fu_674_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= real_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        c0_2_reg_1000 <= c0_2_fu_699_p2;
        c1_2_reg_1008 <= c1_2_fu_706_p2;
        cm2_addr_reg_990 <= zext_ln156_fu_689_p1;
        cm3_addr_reg_995 <= zext_ln157_fu_694_p1;
        est_1_reg_1016 <= est_1_fu_739_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((valid_read_reg_919_pp0_iter18_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cm0_addr_reg_980 <= zext_ln154_fu_679_p1;
        cm1_addr_reg_985 <= zext_ln155_fu_684_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        est_reg_1022 <= est_fu_899_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (valid_read_reg_919 == 1'd1))) begin
        h1_13_reg_960 <= h1_13_fu_525_p2;
        out_reg_945 <= out_fu_352_p2;
        xor_ln12_1_reg_950 <= xor_ln12_1_fu_427_p2;
        xor_ln12_2_reg_955 <= xor_ln12_2_fu_502_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (valid_read_reg_919 == 1'd1))) begin
        h1_1_reg_940 <= h1_1_fu_275_p2;
        or_ln5_i_reg_933 <= or_ln5_i_fu_249_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        key_read_reg_914 <= key_dout;
        key_read_reg_914_pp0_iter10_reg <= key_read_reg_914_pp0_iter9_reg;
        key_read_reg_914_pp0_iter11_reg <= key_read_reg_914_pp0_iter10_reg;
        key_read_reg_914_pp0_iter12_reg <= key_read_reg_914_pp0_iter11_reg;
        key_read_reg_914_pp0_iter13_reg <= key_read_reg_914_pp0_iter12_reg;
        key_read_reg_914_pp0_iter14_reg <= key_read_reg_914_pp0_iter13_reg;
        key_read_reg_914_pp0_iter15_reg <= key_read_reg_914_pp0_iter14_reg;
        key_read_reg_914_pp0_iter16_reg <= key_read_reg_914_pp0_iter15_reg;
        key_read_reg_914_pp0_iter17_reg <= key_read_reg_914_pp0_iter16_reg;
        key_read_reg_914_pp0_iter18_reg <= key_read_reg_914_pp0_iter17_reg;
        key_read_reg_914_pp0_iter19_reg <= key_read_reg_914_pp0_iter18_reg;
        key_read_reg_914_pp0_iter1_reg <= key_read_reg_914;
        key_read_reg_914_pp0_iter20_reg <= key_read_reg_914_pp0_iter19_reg;
        key_read_reg_914_pp0_iter2_reg <= key_read_reg_914_pp0_iter1_reg;
        key_read_reg_914_pp0_iter3_reg <= key_read_reg_914_pp0_iter2_reg;
        key_read_reg_914_pp0_iter4_reg <= key_read_reg_914_pp0_iter3_reg;
        key_read_reg_914_pp0_iter5_reg <= key_read_reg_914_pp0_iter4_reg;
        key_read_reg_914_pp0_iter6_reg <= key_read_reg_914_pp0_iter5_reg;
        key_read_reg_914_pp0_iter7_reg <= key_read_reg_914_pp0_iter6_reg;
        key_read_reg_914_pp0_iter8_reg <= key_read_reg_914_pp0_iter7_reg;
        key_read_reg_914_pp0_iter9_reg <= key_read_reg_914_pp0_iter8_reg;
        valid_read_reg_919 <= valid_dout;
        valid_read_reg_919_pp0_iter10_reg <= valid_read_reg_919_pp0_iter9_reg;
        valid_read_reg_919_pp0_iter11_reg <= valid_read_reg_919_pp0_iter10_reg;
        valid_read_reg_919_pp0_iter12_reg <= valid_read_reg_919_pp0_iter11_reg;
        valid_read_reg_919_pp0_iter13_reg <= valid_read_reg_919_pp0_iter12_reg;
        valid_read_reg_919_pp0_iter14_reg <= valid_read_reg_919_pp0_iter13_reg;
        valid_read_reg_919_pp0_iter15_reg <= valid_read_reg_919_pp0_iter14_reg;
        valid_read_reg_919_pp0_iter16_reg <= valid_read_reg_919_pp0_iter15_reg;
        valid_read_reg_919_pp0_iter17_reg <= valid_read_reg_919_pp0_iter16_reg;
        valid_read_reg_919_pp0_iter18_reg <= valid_read_reg_919_pp0_iter17_reg;
        valid_read_reg_919_pp0_iter19_reg <= valid_read_reg_919_pp0_iter18_reg;
        valid_read_reg_919_pp0_iter1_reg <= valid_read_reg_919;
        valid_read_reg_919_pp0_iter20_reg <= valid_read_reg_919_pp0_iter19_reg;
        valid_read_reg_919_pp0_iter2_reg <= valid_read_reg_919_pp0_iter1_reg;
        valid_read_reg_919_pp0_iter3_reg <= valid_read_reg_919_pp0_iter2_reg;
        valid_read_reg_919_pp0_iter4_reg <= valid_read_reg_919_pp0_iter3_reg;
        valid_read_reg_919_pp0_iter5_reg <= valid_read_reg_919_pp0_iter4_reg;
        valid_read_reg_919_pp0_iter6_reg <= valid_read_reg_919_pp0_iter5_reg;
        valid_read_reg_919_pp0_iter7_reg <= valid_read_reg_919_pp0_iter6_reg;
        valid_read_reg_919_pp0_iter8_reg <= valid_read_reg_919_pp0_iter7_reg;
        valid_read_reg_919_pp0_iter9_reg <= valid_read_reg_919_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((valid_read_read_fu_114_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        lshr_ln5_i_reg_923 <= {{k1_fu_179_p2[31:17]}};
        tmp_16_i_reg_928 <= {{mul_ln5_fu_185_p2[31:15]}};
    end
end

always @ (posedge ap_clk) begin
    if (((valid_read_reg_919_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        out_7_reg_970 <= out_7_fu_586_p2;
        out_8_reg_975 <= out_8_fu_663_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = real_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (real_start == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to19 = 1'b1;
    end else begin
        ap_idle_pp0_0to19 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to20 = 1'b1;
    end else begin
        ap_idle_pp0_1to20 = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0_0to19 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (valid_read_reg_919_pp0_iter20_reg == 1'd1))) begin
        candidate_stream_blk_n = candidate_stream_full_n;
    end else begin
        candidate_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (valid_read_reg_919_pp0_iter20_reg == 1'd1))) begin
        candidate_stream_write = 1'b1;
    end else begin
        candidate_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter19 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            cm0_address0 = cm0_addr_reg_980;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            cm0_address0 = zext_ln154_fu_679_p1;
        end else begin
            cm0_address0 = 'bx;
        end
    end else begin
        cm0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        cm0_ce0 = 1'b1;
    end else begin
        cm0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        cm0_we0 = 1'b1;
    end else begin
        cm0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter19 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            cm1_address0 = cm1_addr_reg_985;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            cm1_address0 = zext_ln155_fu_684_p1;
        end else begin
            cm1_address0 = 'bx;
        end
    end else begin
        cm1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        cm1_ce0 = 1'b1;
    end else begin
        cm1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        cm1_we0 = 1'b1;
    end else begin
        cm1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        cm2_address0 = cm2_addr_reg_990;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        cm2_address0 = zext_ln156_fu_689_p1;
    end else begin
        cm2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cm2_ce0 = 1'b1;
    end else begin
        cm2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cm2_we0 = 1'b1;
    end else begin
        cm2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        cm3_address0 = cm3_addr_reg_995;
    end else if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        cm3_address0 = zext_ln157_fu_694_p1;
    end else begin
        cm3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter20 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cm3_ce0 = 1'b1;
    end else begin
        cm3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter20 == 1'b1) & (valid_read_reg_919_pp0_iter19_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        cm3_we0 = 1'b1;
    end else begin
        cm3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_531_ce = 1'b1;
    end else begin
        grp_fu_531_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_561_ce = 1'b1;
    end else begin
        grp_fu_561_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_669_ce = 1'b1;
    end else begin
        grp_fu_669_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)))) begin
        grp_fu_674_ce = 1'b1;
    end else begin
        grp_fu_674_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        key_blk_n = key_empty_n;
    end else begin
        key_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        key_read = 1'b1;
    end else begin
        key_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (ap_done_reg == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        valid_blk_n = valid_empty_n;
    end else begin
        valid_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        valid_read = 1'b1;
    end else begin
        valid_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to20 == 1'b1) & (real_start == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_idle_pp0 == 1'b0)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_idle_pp0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_2_fu_369_p2 = ($signed(h1_4_fu_358_p2) + $signed(32'd3864292196));

assign add_ln37_4_fu_444_p2 = ($signed(h1_8_fu_433_p2) + $signed(32'd3864292196));

assign add_ln37_6_fu_519_p2 = ($signed(h1_12_fu_508_p2) + $signed(32'd3864292196));

assign add_ln37_fu_269_p2 = ($signed(h1_fu_257_p2) + $signed(32'd3864292196));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (valid_empty_n == 1'b0) | (key_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter0 == 1'b1) & ((ap_done_reg == 1'b1) | (valid_empty_n == 1'b0) | (key_empty_n == 1'b0))));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = ((ap_enable_reg_pp0_iter20 == 1'b1) & (valid_read_reg_919_pp0_iter20_reg == 1'd1) & (candidate_stream_full_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = ((ap_enable_reg_pp0_iter20 == 1'b1) & (valid_read_reg_919_pp0_iter20_reg == 1'd1) & (candidate_stream_full_n == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((ap_enable_reg_pp0_iter20 == 1'b1) & (valid_read_reg_919_pp0_iter20_reg == 1'd1) & (candidate_stream_full_n == 1'b0));
end

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (valid_empty_n == 1'b0) | (key_empty_n == 1'b0));
end

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage1_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage1_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage1_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage1_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage1_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage1_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage1_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage1_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state42_pp0_stage1_iter20 = ((valid_read_reg_919_pp0_iter20_reg == 1'd1) & (candidate_stream_full_n == 1'b0));
end

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign c0_2_fu_699_p2 = (cm0_q0 + 32'd1);

assign c1_2_fu_706_p2 = (cm1_q0 + 32'd1);

assign c2_2_fu_747_p2 = (cm2_q0 + 32'd1);

assign c3_2_fu_754_p2 = (cm3_q0 + 32'd1);

assign candidate_stream_din = {{est_reg_1022}, {key_read_reg_914_pp0_iter20_reg}};

assign est_1_fu_739_p3 = ((icmp_ln208_fu_733_p2[0:0] == 1'b1) ? trunc_ln7_i_fu_723_p4 : trunc_ln_i_fu_713_p4);

assign est_2_fu_864_p3 = ((icmp_ln211_fu_859_p2[0:0] == 1'b1) ? trunc_ln8_i_fu_849_p4 : est_1_reg_1016);

assign est_3_fu_887_p3 = ((icmp_ln214_fu_881_p2[0:0] == 1'b1) ? trunc_ln9_i_fu_871_p4 : est_2_fu_864_p3);

assign est_fu_899_p3 = ((icmp_ln204_fu_843_p2[0:0] == 1'b1) ? zext_ln197_fu_895_p1 : minv_fu_829_p3);

assign grp_fu_531_p1 = 32'd14336;

assign grp_fu_561_p0 = (zext_ln14_1_fu_551_p1 ^ mul_ln13_1_fu_536_p2);

assign grp_fu_561_p1 = 32'd14336;

assign grp_fu_669_p1 = 32'd14336;

assign grp_fu_674_p1 = 32'd14336;

assign h1_10_fu_456_p2 = (h1_9_fu_450_p2 ^ 32'd4);

assign h1_12_fu_508_p2 = (or_ln5_i_reg_933 ^ 32'd32768);

assign h1_13_fu_525_p2 = (add_ln37_6_fu_519_p2 + shl_ln37_3_fu_513_p2);

assign h1_14_fu_592_p2 = (h1_13_reg_960 ^ 32'd4);

assign h1_1_fu_275_p2 = (add_ln37_fu_269_p2 + shl_ln37_fu_263_p2);

assign h1_2_fu_281_p2 = (h1_1_reg_940 ^ 32'd4);

assign h1_4_fu_358_p2 = (or_ln5_i_reg_933 ^ 32'd16384);

assign h1_5_fu_375_p2 = (add_ln37_2_fu_369_p2 + shl_ln37_1_fu_363_p2);

assign h1_6_fu_381_p2 = (h1_5_fu_375_p2 ^ 32'd4);

assign h1_8_fu_433_p2 = (or_ln5_i_reg_933 ^ 32'd24576);

assign h1_9_fu_450_p2 = (add_ln37_4_fu_444_p2 + shl_ln37_2_fu_438_p2);

assign h1_fu_257_p2 = (or_ln5_i_fu_249_p3 ^ 32'd8192);

assign icmp_ln177_fu_761_p2 = ((c1_2_reg_1008 > c0_2_reg_1000) ? 1'b1 : 1'b0);

assign icmp_ln180_fu_771_p2 = ((c2_2_fu_747_p2 > maxv_fu_765_p3) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_785_p2 = ((c3_2_fu_754_p2 > maxv_2_fu_777_p3) ? 1'b1 : 1'b0);

assign icmp_ln187_fu_799_p2 = ((c1_2_reg_1008 < c0_2_reg_1000) ? 1'b1 : 1'b0);

assign icmp_ln190_fu_809_p2 = ((c2_2_fu_747_p2 < minv_2_fu_803_p3) ? 1'b1 : 1'b0);

assign icmp_ln193_fu_823_p2 = ((c3_2_fu_754_p2 < minv_3_fu_815_p3) ? 1'b1 : 1'b0);

assign icmp_ln204_fu_843_p2 = ((sub_ln204_fu_837_p2 > 32'd3000) ? 1'b1 : 1'b0);

assign icmp_ln208_fu_733_p2 = ((trunc_ln7_i_fu_723_p4 < trunc_ln_i_fu_713_p4) ? 1'b1 : 1'b0);

assign icmp_ln211_fu_859_p2 = ((trunc_ln8_i_fu_849_p4 < est_1_reg_1016) ? 1'b1 : 1'b0);

assign icmp_ln214_fu_881_p2 = ((trunc_ln9_i_fu_871_p4 < est_2_fu_864_p3) ? 1'b1 : 1'b0);

assign k1_1_fu_211_p3 = {{tmp_16_i_reg_928}, {lshr_ln5_i_reg_923}};

assign k1_2_fu_217_p1 = 32'd461845907;

assign k1_fu_179_p1 = 32'd3432918353;

assign lshr_ln10_1_i_fu_387_p4 = {{h1_6_fu_381_p2[31:16]}};

assign lshr_ln10_2_i_fu_462_p4 = {{h1_10_fu_456_p2[31:16]}};

assign lshr_ln10_3_i_fu_597_p4 = {{h1_14_fu_592_p2[31:16]}};

assign lshr_ln12_1_i_fu_413_p4 = {{mul_ln11_1_fu_407_p2[31:13]}};

assign lshr_ln12_2_i_fu_488_p4 = {{mul_ln11_2_fu_482_p2[31:13]}};

assign lshr_ln12_3_i_fu_623_p4 = {{mul_ln11_3_fu_617_p2[31:13]}};

assign lshr_ln14_1_i_fu_541_p4 = {{mul_ln13_1_fu_536_p2[31:16]}};

assign lshr_ln14_2_i_fu_572_p4 = {{mul_ln13_2_fu_567_p2[31:16]}};

assign lshr_ln14_3_i_fu_649_p4 = {{mul_ln13_3_fu_643_p2[31:16]}};

assign lshr_ln1_i_fu_312_p4 = {{mul_ln11_fu_306_p2[31:13]}};

assign lshr_ln2_i_fu_338_p4 = {{mul_ln13_fu_332_p2[31:16]}};

assign lshr_ln5_1_i_fu_229_p4 = {{k1_2_fu_217_p2[31:19]}};

assign lshr_ln_i_fu_286_p4 = {{h1_2_fu_281_p2[31:16]}};

assign maxv_2_fu_777_p3 = ((icmp_ln180_fu_771_p2[0:0] == 1'b1) ? c2_2_fu_747_p2 : maxv_fu_765_p3);

assign maxv_3_fu_791_p3 = ((icmp_ln183_fu_785_p2[0:0] == 1'b1) ? c3_2_fu_754_p2 : maxv_2_fu_777_p3);

assign maxv_fu_765_p3 = ((icmp_ln177_fu_761_p2[0:0] == 1'b1) ? c1_2_reg_1008 : c0_2_reg_1000);

assign minv_2_fu_803_p3 = ((icmp_ln187_fu_799_p2[0:0] == 1'b1) ? c1_2_reg_1008 : c0_2_reg_1000);

assign minv_3_fu_815_p3 = ((icmp_ln190_fu_809_p2[0:0] == 1'b1) ? c2_2_fu_747_p2 : minv_2_fu_803_p3);

assign minv_fu_829_p3 = ((icmp_ln193_fu_823_p2[0:0] == 1'b1) ? c3_2_fu_754_p2 : minv_3_fu_815_p3);

assign mul_ln11_1_fu_407_p0 = (zext_ln10_1_fu_397_p1 ^ h1_6_fu_381_p2);

assign mul_ln11_2_fu_482_p0 = (zext_ln10_2_fu_472_p1 ^ h1_10_fu_456_p2);

assign mul_ln11_3_fu_617_p0 = (zext_ln10_3_fu_607_p1 ^ h1_14_fu_592_p2);

assign mul_ln11_fu_306_p0 = (zext_ln10_fu_296_p1 ^ h1_2_fu_281_p2);

assign mul_ln13_1_fu_536_p1 = 32'd3266489909;

assign mul_ln13_2_fu_567_p1 = 32'd3266489909;

assign mul_ln13_3_fu_643_p0 = (zext_ln12_3_fu_633_p1 ^ mul_ln11_3_fu_617_p2);

assign mul_ln13_3_fu_643_p1 = 32'd3266489909;

assign mul_ln13_fu_332_p0 = (zext_ln12_fu_322_p1 ^ mul_ln11_fu_306_p2);

assign mul_ln13_fu_332_p1 = 32'd3266489909;

assign mul_ln5_1_fu_223_p1 = 32'd3870449664;

assign mul_ln5_fu_185_p1 = 32'd380141568;

assign or_ln5_i_fu_249_p3 = {{tmp_18_i_fu_239_p4}, {lshr_ln5_1_i_fu_229_p4}};

assign out_7_fu_586_p2 = (zext_ln14_2_fu_582_p1 ^ mul_ln13_2_fu_567_p2);

assign out_8_fu_663_p2 = (zext_ln14_3_fu_659_p1 ^ mul_ln13_3_fu_643_p2);

assign out_fu_352_p2 = (zext_ln14_fu_348_p1 ^ mul_ln13_fu_332_p2);

assign shl_ln37_1_fu_363_p2 = h1_4_fu_358_p2 << 32'd2;

assign shl_ln37_2_fu_438_p2 = h1_8_fu_433_p2 << 32'd2;

assign shl_ln37_3_fu_513_p2 = h1_12_fu_508_p2 << 32'd2;

assign shl_ln37_fu_263_p2 = h1_fu_257_p2 << 32'd2;

assign start_out = real_start;

assign sub_ln204_fu_837_p2 = (maxv_3_fu_791_p3 - minv_fu_829_p3);

assign tmp_18_i_fu_239_p4 = {{mul_ln5_1_fu_223_p2[31:13]}};

assign trunc_ln7_i_fu_723_p4 = {{c1_2_fu_706_p2[31:1]}};

assign trunc_ln8_i_fu_849_p4 = {{c2_2_fu_747_p2[31:1]}};

assign trunc_ln9_i_fu_871_p4 = {{c3_2_fu_754_p2[31:1]}};

assign trunc_ln_i_fu_713_p4 = {{c0_2_fu_699_p2[31:1]}};

assign valid_read_read_fu_114_p2 = valid_dout;

assign xor_ln12_1_fu_427_p2 = (zext_ln12_1_fu_423_p1 ^ mul_ln11_1_fu_407_p2);

assign xor_ln12_2_fu_502_p2 = (zext_ln12_2_fu_498_p1 ^ mul_ln11_2_fu_482_p2);

assign zext_ln10_1_fu_397_p1 = lshr_ln10_1_i_fu_387_p4;

assign zext_ln10_2_fu_472_p1 = lshr_ln10_2_i_fu_462_p4;

assign zext_ln10_3_fu_607_p1 = lshr_ln10_3_i_fu_597_p4;

assign zext_ln10_fu_296_p1 = lshr_ln_i_fu_286_p4;

assign zext_ln12_1_fu_423_p1 = lshr_ln12_1_i_fu_413_p4;

assign zext_ln12_2_fu_498_p1 = lshr_ln12_2_i_fu_488_p4;

assign zext_ln12_3_fu_633_p1 = lshr_ln12_3_i_fu_623_p4;

assign zext_ln12_fu_322_p1 = lshr_ln1_i_fu_312_p4;

assign zext_ln14_1_fu_551_p1 = lshr_ln14_1_i_fu_541_p4;

assign zext_ln14_2_fu_582_p1 = lshr_ln14_2_i_fu_572_p4;

assign zext_ln14_3_fu_659_p1 = lshr_ln14_3_i_fu_649_p4;

assign zext_ln14_fu_348_p1 = lshr_ln2_i_fu_338_p4;

assign zext_ln154_fu_679_p1 = grp_fu_531_p2;

assign zext_ln155_fu_684_p1 = grp_fu_561_p2;

assign zext_ln156_fu_689_p1 = grp_fu_669_p2;

assign zext_ln157_fu_694_p1 = grp_fu_674_p2;

assign zext_ln197_fu_895_p1 = est_3_fu_887_p3;

endmodule //topk_cm_stage
