// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="LFE_LFE,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu280-fsvh2892-2L-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.340000,HLS_SYN_LAT=3,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=165,HLS_SYN_LUT=763,HLS_VERSION=2020_2}" *)

module LFE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        src,
        src_ap_vld,
        dst,
        dst_ap_vld,
        src_o,
        dst_o,
        cnt
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] src;
input   src_ap_vld;
input  [31:0] dst;
input   dst_ap_vld;
input  [31:0] src_o;
input  [31:0] dst_o;
input  [31:0] cnt;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] src_preg;
reg  signed [31:0] src_in_sig;
reg    src_ap_vld_preg;
reg    src_ap_vld_in_sig;
reg   [15:0] A_address0;
reg    A_ce0;
reg    A_we0;
wire   [31:0] A_d0;
wire   [31:0] A_q0;
reg   [15:0] A_address1;
reg    A_ce1;
reg    A_we1;
wire   [31:0] A_d1;
wire   [31:0] A_q1;
reg    src_blk_n;
reg   [12:0] lshr_ln4_1_reg_427;
reg   [18:0] tmp_3_reg_432;
wire  signed [31:0] xor_ln11_fu_265_p2;
reg  signed [31:0] xor_ln11_reg_437;
wire    ap_CS_fsm_state2;
wire  signed [31:0] xor_ln11_1_fu_341_p2;
reg  signed [31:0] xor_ln11_1_reg_442;
reg   [15:0] A_addr_reg_447;
wire    ap_CS_fsm_state3;
reg   [15:0] A_addr_1_reg_452;
wire   [63:0] zext_ln21_fu_372_p1;
wire   [63:0] zext_ln23_fu_408_p1;
reg    ap_block_state1;
wire    ap_CS_fsm_state4;
wire  signed [30:0] k1_1_fu_117_p1;
wire   [29:0] mul_ln4_fu_123_p1;
wire   [31:0] k1_1_fu_117_p2;
wire   [31:0] mul_ln4_fu_123_p2;
wire   [16:0] tmp_1_fu_139_p4;
wire   [14:0] lshr_ln4_fu_129_p4;
wire  signed [31:0] k1_fu_149_p3;
wire   [29:0] k1_2_fu_157_p1;
wire  signed [29:0] mul_ln4_1_fu_163_p1;
wire   [31:0] k1_2_fu_157_p2;
wire   [31:0] mul_ln4_1_fu_163_p2;
wire   [31:0] or_ln4_fu_189_p3;
wire   [31:0] h1_fu_195_p2;
wire   [31:0] add_ln34_fu_207_p2;
wire   [31:0] shl_ln34_fu_201_p2;
wire   [31:0] h1_1_fu_213_p2;
wire   [31:0] h1_2_fu_219_p2;
wire   [15:0] lshr_ln9_fu_225_p4;
wire   [31:0] zext_ln9_fu_235_p1;
wire  signed [31:0] mul_ln10_fu_245_p0;
wire   [31:0] mul_ln10_fu_245_p2;
wire   [18:0] lshr_ln_fu_251_p4;
wire   [31:0] zext_ln11_fu_261_p1;
wire   [31:0] h1_4_fu_271_p2;
wire   [31:0] add_ln34_2_fu_283_p2;
wire   [31:0] shl_ln34_1_fu_277_p2;
wire   [31:0] h1_5_fu_289_p2;
wire   [31:0] h1_6_fu_295_p2;
wire   [15:0] lshr_ln9_1_fu_301_p4;
wire   [31:0] zext_ln9_1_fu_311_p1;
wire  signed [31:0] mul_ln10_1_fu_321_p0;
wire   [31:0] mul_ln10_1_fu_321_p2;
wire   [18:0] lshr_ln11_1_fu_327_p4;
wire   [31:0] zext_ln11_1_fu_337_p1;
wire  signed [30:0] mul_ln12_fu_347_p1;
wire   [31:0] mul_ln12_fu_347_p2;
wire   [15:0] trunc_ln_fu_356_p4;
wire   [15:0] trunc_ln7_fu_352_p1;
wire   [15:0] out_fu_366_p2;
wire  signed [30:0] mul_ln12_1_fu_377_p1;
wire   [31:0] mul_ln12_1_fu_377_p2;
wire   [15:0] trunc_ln13_1_fu_386_p4;
wire   [15:0] trunc_ln7_1_fu_382_p1;
wire   [15:0] out1_fu_396_p2;
wire   [15:0] xor_ln23_fu_402_p2;
reg   [3:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 src_preg = 32'd0;
#0 src_ap_vld_preg = 1'b0;
end

LFE_A #(
    .DataWidth( 32 ),
    .AddressRange( 65536 ),
    .AddressWidth( 16 ))
A_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(A_address0),
    .ce0(A_ce0),
    .we0(A_we0),
    .d0(A_d0),
    .q0(A_q0),
    .address1(A_address1),
    .ce1(A_ce1),
    .we1(A_we1),
    .d1(A_d1),
    .q1(A_q1)
);

LFE_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U1(
    .din0(src_in_sig),
    .din1(k1_1_fu_117_p1),
    .dout(k1_1_fu_117_p2)
);

LFE_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U2(
    .din0(src_in_sig),
    .din1(mul_ln4_fu_123_p1),
    .dout(mul_ln4_fu_123_p2)
);

LFE_mul_32s_30ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30ns_32_1_1_U3(
    .din0(k1_fu_149_p3),
    .din1(k1_2_fu_157_p1),
    .dout(k1_2_fu_157_p2)
);

LFE_mul_32s_30s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 32 ))
mul_32s_30s_32_1_1_U4(
    .din0(k1_fu_149_p3),
    .din1(mul_ln4_1_fu_163_p1),
    .dout(mul_ln4_1_fu_163_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U5(
    .din0(mul_ln10_fu_245_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_fu_245_p2)
);

LFE_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U6(
    .din0(mul_ln10_1_fu_321_p0),
    .din1(32'd2246822507),
    .dout(mul_ln10_1_fu_321_p2)
);

LFE_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U7(
    .din0(xor_ln11_reg_437),
    .din1(mul_ln12_fu_347_p1),
    .dout(mul_ln12_fu_347_p2)
);

LFE_mul_32s_31s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
mul_32s_31s_32_1_1_U8(
    .din0(xor_ln11_1_reg_442),
    .din1(mul_ln12_1_fu_377_p1),
    .dout(mul_ln12_1_fu_377_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        src_ap_vld_preg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            src_ap_vld_preg <= 1'b0;
        end else if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (src_ap_vld == 1'b1))) begin
            src_ap_vld_preg <= src_ap_vld;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        src_preg <= 32'd0;
    end else begin
        if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (src_ap_vld == 1'b1))) begin
            src_preg <= src;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_addr_1_reg_452 <= zext_ln23_fu_408_p1;
        A_addr_reg_447 <= zext_ln21_fu_372_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        lshr_ln4_1_reg_427 <= {{k1_2_fu_157_p2[31:19]}};
        tmp_3_reg_432 <= {{mul_ln4_1_fu_163_p2[31:13]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        xor_ln11_1_reg_442 <= xor_ln11_1_fu_341_p2;
        xor_ln11_reg_437 <= xor_ln11_fu_265_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address0 = A_addr_1_reg_452;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address0 = zext_ln23_fu_408_p1;
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_address1 = A_addr_reg_447;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        A_address1 = zext_ln21_fu_372_p1;
    end else begin
        A_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        A_ce1 = 1'b1;
    end else begin
        A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_we0 = 1'b1;
    end else begin
        A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        A_we1 = 1'b1;
    end else begin
        A_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((src_ap_vld == 1'b1)) begin
        src_ap_vld_in_sig = src_ap_vld;
    end else begin
        src_ap_vld_in_sig = src_ap_vld_preg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        src_blk_n = src_ap_vld;
    end else begin
        src_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((src_ap_vld == 1'b1)) begin
        src_in_sig = src;
    end else begin
        src_in_sig = src_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (src_ap_vld_in_sig == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_d0 = (A_q0 + 32'd1);

assign A_d1 = (A_q1 + 32'd1);

assign add_ln34_2_fu_283_p2 = ($signed(h1_4_fu_271_p2) + $signed(32'd3864292196));

assign add_ln34_fu_207_p2 = ($signed(h1_fu_195_p2) + $signed(32'd3864292196));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (src_ap_vld_in_sig == 1'b0));
end

assign h1_1_fu_213_p2 = (add_ln34_fu_207_p2 + shl_ln34_fu_201_p2);

assign h1_2_fu_219_p2 = (h1_1_fu_213_p2 ^ 32'd4);

assign h1_4_fu_271_p2 = (or_ln4_fu_189_p3 ^ 32'd16384);

assign h1_5_fu_289_p2 = (add_ln34_2_fu_283_p2 + shl_ln34_1_fu_277_p2);

assign h1_6_fu_295_p2 = (h1_5_fu_289_p2 ^ 32'd4);

assign h1_fu_195_p2 = (or_ln4_fu_189_p3 ^ 32'd8192);

assign k1_1_fu_117_p1 = 32'd3432918353;

assign k1_2_fu_157_p1 = 32'd461845907;

assign k1_fu_149_p3 = {{tmp_1_fu_139_p4}, {lshr_ln4_fu_129_p4}};

assign lshr_ln11_1_fu_327_p4 = {{mul_ln10_1_fu_321_p2[31:13]}};

assign lshr_ln4_fu_129_p4 = {{k1_1_fu_117_p2[31:17]}};

assign lshr_ln9_1_fu_301_p4 = {{h1_6_fu_295_p2[31:16]}};

assign lshr_ln9_fu_225_p4 = {{h1_2_fu_219_p2[31:16]}};

assign lshr_ln_fu_251_p4 = {{mul_ln10_fu_245_p2[31:13]}};

assign mul_ln10_1_fu_321_p0 = (zext_ln9_1_fu_311_p1 ^ h1_6_fu_295_p2);

assign mul_ln10_fu_245_p0 = (zext_ln9_fu_235_p1 ^ h1_2_fu_219_p2);

assign mul_ln12_1_fu_377_p1 = 32'd3266489909;

assign mul_ln12_fu_347_p1 = 32'd3266489909;

assign mul_ln4_1_fu_163_p1 = 32'd3870449664;

assign mul_ln4_fu_123_p1 = 32'd380141568;

assign or_ln4_fu_189_p3 = {{tmp_3_reg_432}, {lshr_ln4_1_reg_427}};

assign out1_fu_396_p2 = (trunc_ln7_1_fu_382_p1 ^ trunc_ln13_1_fu_386_p4);

assign out_fu_366_p2 = (trunc_ln_fu_356_p4 ^ trunc_ln7_fu_352_p1);

assign shl_ln34_1_fu_277_p2 = h1_4_fu_271_p2 << 32'd2;

assign shl_ln34_fu_201_p2 = h1_fu_195_p2 << 32'd2;

assign tmp_1_fu_139_p4 = {{mul_ln4_fu_123_p2[31:15]}};

assign trunc_ln13_1_fu_386_p4 = {{mul_ln12_1_fu_377_p2[31:16]}};

assign trunc_ln7_1_fu_382_p1 = mul_ln12_1_fu_377_p2[15:0];

assign trunc_ln7_fu_352_p1 = mul_ln12_fu_347_p2[15:0];

assign trunc_ln_fu_356_p4 = {{mul_ln12_fu_347_p2[31:16]}};

assign xor_ln11_1_fu_341_p2 = (zext_ln11_1_fu_337_p1 ^ mul_ln10_1_fu_321_p2);

assign xor_ln11_fu_265_p2 = (zext_ln11_fu_261_p1 ^ mul_ln10_fu_245_p2);

assign xor_ln23_fu_402_p2 = (out1_fu_396_p2 ^ 16'd32768);

assign zext_ln11_1_fu_337_p1 = lshr_ln11_1_fu_327_p4;

assign zext_ln11_fu_261_p1 = lshr_ln_fu_251_p4;

assign zext_ln21_fu_372_p1 = out_fu_366_p2;

assign zext_ln23_fu_408_p1 = xor_ln23_fu_402_p2;

assign zext_ln9_1_fu_311_p1 = lshr_ln9_1_fu_301_p4;

assign zext_ln9_fu_235_p1 = lshr_ln9_fu_225_p4;

endmodule //LFE
